### ISSUE TITLE
[design] - Quora Indonesia 

### ISSUE THREAD

**Issue by naufaldi** [mazipan/login-page-css#23]
![Screen Shot 2020-10-05 at 21 26 43](https://user-images.githubusercontent.com/13159420/95092117-7a44b280-0751-11eb-92ea-d1517d10c09d.png)

Login url : [Quora Indonesia ](https://id.quora.com/)

can i take this design? 

Thanks.

**Comment by mazipan** [comment]
Ah this is very cool page.
Take it please 🙌

Note: please do not use your `master` branch to create a PR, create another branch first before start working

**Comment by mazipan** [comment]
Jadi ngerjain ini @naufaldi ?

**Comment by naufaldi** [comment]
Jadi mas, minggu sepertinya selesai. Baru bisa ngerjain pas weekend. hehe

**Comment by mazipan** [comment]
Close on #47
