### ISSUE TITLE
[design] - Paypal

### ISSUE THREAD

**Issue by Fadil3** [mazipan/login-page-css#25]
login URL: https://www.paypal.com/en/signin
![zzz](https://user-images.githubusercontent.com/55126764/95095578-6ac76880-0755-11eb-83b8-238201108e73.PNG)
can I take this, sir?

**Comment by mazipan** [comment]
Yah, this is cool 👍

**Comment by mazipan** [comment]
Note: please do not use your master branch to create a PR, create another branch first before start working

**Comment by mazipan** [comment]
Terima kasih 🙌
