### ISSUE TITLE
[design] - Netflix

### ISSUE THREAD

**Issue by SubhamKarmakar24** [mazipan/login-page-css#77]
**Is your feature request related to a problem? Please describe.**
Netflix is one of the popular websites. Thus its login page needs to be added.

**Describe the solution you'd like**
Make a clone of [Netflix](https://www.netflix.com/in/login) login page

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by SubhamKarmakar24** [comment]
Is this repository accepting PRs for Hacktoberfest 2021? @mazipan I would like to add some cool website login pages to this repository

**Comment by mazipan** [comment]
Not sure, still not read the rule for Hacktoberfest for this year

**Comment by SubhamKarmakar24** [comment]
> 
> 
> Not sure, still not read the rule for Hacktoberfest for this year

Rules are almost same. The repository must have hacktoberfest topic, and the PRs must be approved or labelled as hacktoberfest-accepted to count as valid PR

**Comment by mazipan** [comment]
I think we have `hacktoberfest` topic from last year.
So unless the Hacktoberfest not mark this repo as invalid/spam repo, we are good to go to for hacktobefest.

Just remind me to adding a label if you need it

**Comment by SubhamKarmakar24** [comment]
> 
> 
> I think we have `hacktoberfest` topic from last year. So unless the Hacktoberfest team did not mark this repo as invalid/spam repo, we are good to go to for hacktobefest.
> 
> please remind me to adding a label if you need it

Sure, thank you!
